/*
* CANBadger PIDs
* Copyright (c) 2021 Noelscher Consulting GmbH
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
* THE SOFTWARE.
*/

//PIDs
#define PID_POWERTRAIN_DIAGNOSTIC_REQUEST 0x1
#define PID_POWERTRAIN_FREEZE_FRAME_REQUEST 0x2
#define PID_EMISSIONS_DTC_REQUEST 0x3
#define PID_EMISSIONS_DTC_CLEAR 0x04
#define PID_OXYGEN_SENSOR_TEST 0x5 //THIS IS CAN ONLY
#define PID_TEST_RESULTS 0x6
#define PID_DRIVE_CYCLE_DTC_REQUEST 0x7
#define PID_CONTROL 0x8
#define PID_VEHICLE_INFORMATION 0x9
#define PID_PERMANENT_DTC_REQUEST 0xa
#define PID_ENHANCED_DIAGNOSTIC_REQUEST 0x22



// Mode 1 PIDs

#define PID_SUPPORTED_PIDS_1_20 0x00
#define PID_MONITOR_STATUS 0x01
#define PID_FREEZE_DTC 0x02
#define PID_FUEL_SYSTEM_STATUS 0x03
#define PID_ENGINE_LOAD 0x04
#define PID_COOLANT_TEMP 0x05
#define PID_SHORT_TERM_FUEL_TRIM_1 0x06
#define PID_LONG_TERM_FUEL_TRIM_1 0x07
#define PID_SHORT_TERM_FUEL_TRIM_2 0x08
#define PID_LONG_TERM_FUEL_TRIM_2 0x09
#define PID_FUEL_PRESSURE 0x0A
#define PID_INTAKE_MAP 0x0B
#define PID_RPM 0x0C
#define PID_SPEED 0x0D
#define PID_TIMING_ADVANCE 0x0E
#define PID_INTAKE_TEMP 0x0F
#define PID_MAF_FLOW 0x10
#define PID_THROTTLE 0x11
#define PID_COMMANDED_SECOND_AIR_STAT 0x12
#define PID_OXYGEN_SENSORS_PRESENT 0x13
#define PID_B1S1_O2_V     0x14
#define PID_B1S2_O2_V     0x15
#define PID_B1S3_O2_V     0x16
#define PID_B1S4_O2_V     0x17
#define PID_B2S1_O2_V     0x18
#define PID_B2S2_O2_V     0x19
#define PID_B2S3_O2_V     0x1A
#define PID_B2S4_O2_V     0x1B
#define PID_OBD_STANDARD 0x1C
#define PID_OXYGEN_SENSORS_PRESENT_4 0x1D
#define PID_AUX_INPUT 0x1E
#define PID_RUNTIME 0x1F
#define PID_SUPPORTED_PIDS_21_40 0x20
#define PID_DISTANCE_WITH_MIL 0x21
#define PID_FUEL_RAIL_PRESSURE2 0x22
#define PID_FUEL_RAIL_GAUGE_PRESSURE 0x23
#define PID_OXYGEN_SENSOR_FA_1 0x24
#define PID_OXYGEN_SENSOR_FA_2 0x25
#define PID_OXYGEN_SENSOR_FA_3 0x26
#define PID_OXYGEN_SENSOR_FA_4 0x27
#define PID_OXYGEN_SENSOR_FA_5 0x28
#define PID_OXYGEN_SENSOR_FA_6 0x29
#define PID_OXYGEN_SENSOR_FA_7 0x2A
#define PID_OXYGEN_SENSOR_FA_8 0x2B
#define PID_COMMANDED_EGR 0x2C
#define PID_EGR_ERROR 0x2D
#define PID_COMMANDED_EVAPORATIVE_PURGE 0x2E
#define PID_FUEL_LEVEL 0x2F
#define PID_WARMS_UPS 0x30
#define PID_DISTANCE 0x31
#define PID_EVAP_SYS_VAPOR_PRESSURE 0x32
#define PID_BAROMETRIC 0x33
#define PID_O2S1_WR_C 0x34
#define PID_O2S2_WR_C 0x35
#define PID_O2S3_WR_C 0x36
#define PID_O2S4_WR_C 0x37
#define PID_O2S5_WR_C 0x38
#define PID_O2S6_WR_C 0x39
#define PID_O2S7_WR_C 0x3A
#define PID_O2S8_WR_C 0x3B
#define PID_CATALYST_TEMP_B1S1 0x3C
#define PID_CATALYST_TEMP_B2S1 0x3D
#define PID_CATALYST_TEMP_B1S2 0x3E
#define PID_CATALYST_TEMP_B2S2 0x3F
#define PID_SUPPORTED_PIDS_41_60 0x40
#define PID_MONITOR_STATUS_THIS_DRIVE_CYCLE 0x41
#define PID_CONTROL_MODULE_VOLTAGE 0x42
#define PID_ABSOLUTE_ENGINE_LOAD 0x43
#define PID_AIR_FUEL_EQUIV_RATIO 0x44
#define PID_RELATIVE_THROTTLE_POS 0x45
#define PID_AMBIENT_TEMP 0x46
#define PID_ABSOLUTE_THROTTLE_POS_B 0x47
#define PID_ABSOLUTE_THROTTLE_POS_C 0x48
#define PID_ACC_PEDAL_POS_D 0x49
#define PID_ACC_PEDAL_POS_E 0x4A
#define PID_ACC_PEDAL_POS_F 0x4B
#define PID_COMMANDED_THROTTLE_ACTUATOR 0x4C
#define PID_TIME_WITH_MIL 0x4D
#define PID_TIME_SINCE_CODES_CLEARED 0x4E
#define PID_MAX_VALUE_FUEL_AIR_RATIO_AND_OXYGEN_SENSOR_VOLTAGE_AND_OXYGEN_SENSOR_CURRENT_AND_INTAKE_MANIFOLD_ABSOLUTE_PRESSURE 0x4F
#define PID_FUEL_TYPE 0x51
#define PID_ETHANOL_FUEL 0x52
#define PID_ABSOLUTE_EVAP_SYSTEM_VAPOR_PRESSURE 0x53
#define PID_EVAP_SYSTEM_VAPOR_PRESSURE 0x54
#define PID_SHORT_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_B1_B3 0x55
#define PID_LONG_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_B1_B3 0x56
#define PID_SHORT_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_B2_B4 0x57
#define PID_LONG_TERM_SECONDARY_OXYGEN_SENSOR_TRIM_B2_B4 0x58
#define PID_FUEL_RAIL_PRESSURE 0x59
#define PID_RELATIVE_ACC_PEDAL_POSITION 0x5A
#define PID_HYBRID_BATTERY_PERCENTAGE 0x5B
#define PID_ENGINE_OIL_TEMP 0x5C
#define PID_FUEL_INJECTION_TIMING 0x5D
#define PID_ENGINE_FUEL_RATE 0x5E
#define PID_EMMISION_REQUIREMENTS 0x5F
#define PID_SUPPORTED_PIDS_61_80 0x60
#define PID_ENGINE_TORQUE_DEMANDED 0x61
#define PID_ENGINE_TORQUE_PERCENTAGE 0x62
#define PID_ENGINE_REF_TORQUE 0x63
#define PID_ENGINE_PERCENT_TORQUE 0x64
#define PID_AUXILIARY_IO_SUPPORTED 0x65
#define PID_MAF 0x66
#define PID_ENGINE_COOLANT_TEMP 0x67
#define PID_INTAKE_AIR_TEMP_SENSOR 0x68
#define PID_COMMANDED_EGR_ERROR 0x69
#define PID_COMMANDED_DIESEL_INTAKE_AIRFLOW_AND_RELATIVE_INTAKE_AIRFLOW_POSITION 0x6A
#define PID_EGR_TEMP 0x6B
#define PID_COMMANDED_THROTTLE_ACTUATOR_AND_RELATIVE_THROTTLE_POSITION 0x6C
#define PID_FUEL_PRESSURE_CONTROL_SYSTEM 0x6D
#define PID_INJECTION_PRESSURE_CONTROL_SYSTEM 0x6E
#define PID_TURBO_INLET_PRESSURE 0x6F
#define PID_BOOST_PRESSURE_CONTROL 0x70
#define PID_VGT_CONTROL 0x71
#define PID_WASTEGATE_CONTROL 0x72
#define PID_EXHAUST_PRESSURE 0x73
#define PID_TURBO_RPM 0x74
#define PID_TURBO_TEMP 0x75
#define PID_TURBO_TEMP2 0x76
#define PID_CHARGE_AIR_COOLER_TEMPERATURE 0x77
#define PID_EXHAUST_GAS_TEMPERATURE1 0x78
#define PID_EXHAUST_GAS_TEMPERATURE2 0x79
#define PID_DPF_1 0x7A
#define PID_DPF_2 0X7B
#define PID_DPF_TEMPERATURE 0x7C
#define PID_NOX_NTE_CONTROL_AREA_STATUS 0x7D //NOT TO EXCEED
#define PID_PM_NTE_CONTROL_AREA_STATUS 0x7E
#define PID_ENGINE_RUNTIME 0x7F
#define PID_SUPPORTED_PIDS_81_A0 0x80
#define PID_ENGINE_RUNTIME_FOR_AECD1 0x81 //AUXILIARY EMMISIONS CONTROL DEVICE
#define PID_ENGINE_RUNTIME_FOR_AECD2 0x82
#define PID_NOX_SENSOR 0x83
#define PID_MAN_SURF_TMP  0x84//Manifold surface temp
#define PID_NOX_REAGENT_SYSTEM 0x85
#define PID_PARTICULATE_MATTER_SENSOR 0x86
#define PID_INLET_ABSOLUTE_PRESS 0x87//Inlet Absolute pressure
#define PID_SCR_INDUCE_SYSTEM 0x88
#define PID_RUN_TIME_FOR_AECD_11_15 0x89
#define PID_RUN_TIME_FOR_AECD_16_20 0x8A
#define PID_DIESEL_AFTERTREATMENT 0x8B
#define PID_O2_SENSOR_WIDE_RANGE 0x8C
#define PID_THROTTLE_POSITION_G 0x8D
#define PID_ENGINE_FRICTION_PERCENT_TORQUE 0x8E
#define PID_MP_SENSOR_BANK_1_2 0x8F
#define PID_SUPPORTED_PIDS_A1_C0 0xA0
#define PID_SUPPORTED_PIDS_C1_E0 0xC0
