/**SERVICE IDENTIFIERS FOR UDS PROTOCOL AND THEIR TYPES**/

/*SERVICE IDENTIFIERS*/
#define UDS_DIAGNOSTIC_SESSION_CONTROL 0x10
#define UDS_ECU_RESET 0x11
#define UDS_CLEAR_DIAGNOSTIC_INFORMATION 0x14
#define UDS_SECURITY_ACCESS 0x27
#define UDS_COMMUNICATION_CONTROL 0x28
#define UDS_ACCESS_TIMING_PARAMETERS 0x83
#define UDS_SECURED_DATA_TRANSMISSION 0x84
#define UDS_CONTROL_DTC_SETTINGS 0x85
#define UDS_RESPONSE_ON_EVENT 0x86
#define UDS_LINK_CONTROL 0x87
#define UDS_READ_DATA_BY_ID 0x22
#define UDS_READ_MEMORY_BY_ADDRESS 0x23
#define UDS_READ_SCALING_DATA_BY_ID 0x24
#define UDS_READ_DATA_BY_PERIODIC_ID 0x2A
#define UDS_DYNAMICALLY_DEFINE_DATA_ID 0x2C
#define UDS_WRITE_DATA_BY_ID 0x2E
#define UDS_WRITE_MEMORY_BY_ADDRESS 0x3D
#define UDS_CLEAR_DIAGNOSTIC_INFORMATION 0x14
#define UDS_READ_DTC_INFORMATION 0x19
#define UDS_INPUT_OUTPUT_CONTROL_BY_ID 0x2F
#define UDS_ROUTINE_CONTROL 0x31
#define UDS_REQUEST_DOWNLOAD 0x34
#define UDS_REQUEST_UPLOAD 0x35
#define UDS_TRANSFER_DATA 0x36
#define UDS_REQUEST_TRANSFER_EXIT 0x37
#define UDS_REQUEST_FILE_TRANSFER 0x38
#define UDS_TESTER_PRESENT 0x3E

/*NEGATIVE RESPONSES TO UDS REQUESTS*/
#define UDS_NEGATIVE_RESPONSE 0x7F
#define UDS_GENERAL_REJECT 0x10
#define UDS_SERVICE_NOT_SUPPORTED 0x11
#define UDS_SUBFUNCTION_NOT_SUPPORTED 0x12
#define UDS_INCORRECT_MESSAGE_LENGTH_OR_INVALIDAD_FORMAT 0x13
#define UDS_RESPONSE_TOO_LONG 0x14
#define UDS_BUSY_REPEAT_REQUEST 0x21
#define UDS_CONDITIONS_NOT_CORRECT 0x22
#define UDS_ROUTINE_NOT_COMPLETE 0x23
#define UDS_REQUEST_SEQUENCE_ERROR 0x24
#define UDS_NO_RESPONSE_FROM_SUBNET_COMPONENT 0x25
#define UDS_FAILURE_PREVENTS_EXECUTION_OF_REQUESTED_ACTION 0x26
#define UDS_REQUEST_OUT_OF_RANGE 0x31
#define UDS_SECURITY_ACCESS_DENIED 0x33
#define UDS_INVALID_KEY 0x35
#define UDS_EXCEEDED_NUMBER_OF_ATTEMPTS 0x36
#define UDS_REQUIRED_TIME_DELAY_NOT_EXPIRED 0x37
#define UDS_DOWNLOAD_NOT_ACCEPTED 0x40
#define UDS_IMPROPER_DOWNLOAD_TIME 0x41
#define UDS_CANT_DOWNLOAD_TO_SPECIFIED_ADDRESS 0x42
#define UDS_CANT_DOWNLOAD_NUMBER_OF_BYTES_REQUESTED 0x43
#define UDS_UPLOAD_NOT_ACCEPTED 0x50
#define UDS_IMPROPER_UPLOAD_TYPE 0x51
#define UDS_CANT_UPLOAD_FROM_SPECIFIED_ADDRESS 0x52
#define UDS_CANT_UPLOAD_NUMBER_OF_BYTES_REQUESTED 0x53
//RANGE 0x38-0x4F RESERVED BY ISO 15764
#define UDS_UPLOAD_DOWNLOAD_NOT_ACCEPTED 0x70
#define UDS_TRANSFER_DATA_SUSPENDED 0x71
#define UDS_GENERAL_PROGRAMMING_FAILURE 0x72
#define UDS_WRONG_BLOCK_SEQUENCE_COUNTER 0x73
#define UDS_ILLEGAL_ADDRESS_IN_BLOCK_TRANSFER 0x74
#define UDS_ILLEGAL_BYTE_COUNT_IN_BLOCK_TRANSFER 0x75
#define UDS_ILLEGAL_BLOCK_TRANSFER_TYPE 0x76
#define UDS_BLOCK_TRANSFER_DATA_CHECKSUM_ERROR 0x77
#define UDS_RESPONSE_PENDING 0x78
#define UDS_INCORRECT_BYTE_COUNT_DURING_BLOCK_TRANSFER 0x79
#define UDS_SUBFUNCTION_NOT_SUPPORTED_IN_ACTIVE_SESSION 0x7E
#define UDS_SERVICE_NOT_SUPPORTED_IN_ACTIVE_SESSION 0x7F
#define UDS_SERVICE_NOT_SUPPORTED_IN_ACTIVE_DIAGNOSTIC_MODE 0x80
#define UDS_RPM_TOO_HIGH 0x81
#define UDS_RPM_TOO_LOW 0x82
#define UDS_ENGINE_IS_RUNNING 0x83
#define UDS_ENGINE_IS_NOT_RUNNING 0x84
#define UDS_ENGINE_RUN_TIME_TOO_LOW 0x85
#define UDS_TEMPERATURE_TOO_HIGH 0x86
#define UDS_TEMPERATURE_TOO_LOW 0x87
#define UDS_VEHICLE_SPEED_TOO_HIGH 0x88
#define UDS_VEHICLE_SPEED_TOO_LOW 0x89
#define UDS_THROTTLE_TOO_HIGH 0x8A
#define UDS_THROTTLE_TOO_LOW 0x8B
#define UDS_TRANSMISSION_RANGE_NOT_IN_NEUTRAL 0x8C
#define UDS_TRANSMISSION_RANGE_NOT_IN_GEAR 0x8D
#define UDS_BRAKE_SWITCH_NOT_CLOSED 0x8F
#define UDS_SHIFTER_LEVER_NOT_IN_PARK 0x90
#define UDS_TORQUE_CONVERTER_CLUTCH_LOCKED 0x91
#define UDS_VOLTAGE_TOO_HIGH 0x92
#define UDS_VOLTAGE_TOO_LOW 0x93



/*DIAGNOSTIC SESSION CONTROL TYPES*/
#define UDS_DIAGNOSTIC_DEFAULT_SESSION 0x01
#define UDS_DIAGNOSTIC_PROGRAMMING_SESSION 0x02
#define UDS_DIAGNOSTIC_EXTENDED_SESSION 0x03
#define UDS_DIAGNOSTIC_SAFETY_SYSTEM_SESSION 0x04
//RANGE 0x40-0x5F IS FOR VEHICLE MANUFACTURER SPECIFIC
//RANGE 0x60-0x7E IS FOR SYSTEM SUPPLIER SPECIFIC

/*ECU RESET TYPES*/
#define UDS_ECU_RESET_HARD_RESET 0x01
#define UDS_ECU_RESET_KEY_ON_OFF_RESET 0x02
#define UDS_ECU_RESET_SOFT_RESET 0x03
#define UDS_ECU_RESET_ENABLE_RAPID_POWER_SHUTDOWN 0x04
#define UDS_ECU_RESET_DISABLE_RAPID_POWER_SHUTDOWN 0x05
//RANGE 0x40-0x5F ARE VEHICLE MANUFACTURER SPECIFIC
//RANGE 0x60-0x7E ARE SYSTEM SUPPLIER SPECIFIC

/*COMMUNICATION CONTROL CONTROL TYPES*/
#define UDS_ENABLE_RX_AND_TX 0x00
#define UDS_ENABLE_RX_AND_DISABLE_TX 0x01
#define UDS_DISABLE_RX_AND_ENABLE_TX 0x02
#define UDS_DISABLE_RX_AND_TX 0x03
#define UDS_ENABLE_RX_AND_DISABLE_TX_WITH_ENHANCED_ADDRESS_INFO 0x04
#define UDS_ENABLE_RX_AND_TX_WITH_ENHANCED_ADDRESS_INFO 0x05
//RANGE 0x40-0x5F IS VEHICLE MANUFACTURER SPECIFIC
//RANGE 0x50-0x7E IS SYSTEM SUPPLIER SPECIFIC

/*COMMUNICATION CONTROL TYPES*/
#define UDS_NORMAL_COMMUNICATION_MESSAGES 0x01
#define UDS_NETWORK_MANAGEMENT_COMMUNICATION_MESSAGES 0x02
#define UDS_NETWORK_MANAGEMENT_AND_NORMAL_COMMUNICATION_MESSAGES 0x03
#define UDS_DISABLE_ENABLE_SPECIFIED_COMMUNICATIONTYPE 0x00//this would be bits 4-7
#define UDS_DISABLE_ENABLE_CURRENT_NETWORK 0xF0 //

/*TESTER PRESENT SUB FUNCTION*/
#define UDS_TESTER_PRESENT_ZERO_SUB 0x00 //THIS MEANS THAT THE TESTER EXPECTS A REPLY BACK FROM DUT
#define UDS_TESTER_PRESENT_SUPPRES_POS_RSP_MSG 0x80 //THIS MEANS THAT THE TESTER DOES NOT NEED A POSITIVE REPLY

/*ACCESS TIMING PARAMETER SUBFUCTIONS*/
#define UDS_READ_EXTENDED_TIMING_PARAMETER_SET 0x01
#define UDS_SET_TIMING_PARAMETERS_TO_DEFAULT_VALUES 0x02
#define UDS_READ_CURRENTLY_ACTIVE_TIMING_PARAMETERS 0x03
#define UDS_SET_TIMING_PARAMETERS_TO_GIVEN_VALUES 0x04

/*CONTROL DTC SETTING SUB FUNCTIONS*/
#define UDS_DTC_ON 0x01
#define UDS_DTC_OFF 0x02
//RANGE 0x40-0x5F IS VEHICLE MANUFACTURER SPECIFIC
//RANGE 0x60-0x7E IS SYSTEM SUPPLIER SPECIFIC

/*RESPONSE ON EVENT - EVENT TYPE SUB FUNCTIONS*/
#define UDS_DO_NOT_STORE_EVENT 0x00
#define UDS_STORE_EVENT 0x01

/*RESPONSE ON EVENT - REQUEST SUB FUNCTIONS*/
#define UDS_STOP_RESPONSE_ON_EVENT 0x00
#define UDS_ON_DTC_STATUS_CHANGE 0x01
#define UDS_ON_TIMER_INTERRUPT 0x02
#define UDS_ON_CHANGE_OF_DATA_ID 0x03
#define UDS_REPORT_ACTIVATED_EVENTS 0x04
#define UDS_START_RESPONSE_ON_EVENT 0x05
#define UDS_CLEAR_RESPONSE_ON_EVENT 0x06
#define UDS_ON_COMPARISON_OF_VALUES 0x07
//RANGE 0x20-0x2F IS VEHICLE MANUFACTURER SPECIFIC
//RANGE 0x30-0x3E IS SYSTEM SUPPLIER SPECIFIC

/*LINK CONTROL REQUEST SUB FUNCTIONS*/
#define UDS_VERIFY_BAUDRATE_TRANSITION_WITH_FIXED_BAUDRATE 0x01
#define UDS_VERIFY_MODE_TRANSITION_WITH_FIXED_PARAMETER 0x01
#define UDS_VERIFY_BAUDRATE_TRANSITION_WITH_SPECIFIC_BAUDRATE 0x02
#define UDS_VERIFY_MODE_TRANSITION_WITH_SPECIFIC_PARAMETER 0x02
#define UDS_TRANSITION_BAUDRATE 0x03
#define UDS_TRANSITION_MODE 0x03
//RANGE 0x40-0x5F IS VEHICLE MANUFACTURER SPECIFIC
//RANGE 0x50-0x7E IS SYSTEM SUPPLIER SPECIFIC

/*LINK CONTROL BAUDRATE IDENTIFIER*/
#define UDS_PC9600BAUD     0x01
#define UDS_PC19200BAUD    0x02
#define UDS_PC38400BAUD    0x03
#define UDS_PC57600BAUD    0x04
#define UDS_PC115200BAUD   0x05
#define UDS_CAN125000BAUD  0x10
#define UDS_CAN250000BAUD  0x11
#define UDS_CAN500000BAUD  0x12
#define UDS_CAN1000000BAUD 0x13

/*DYNAMICALLY DEFINE DATA IDENTIFIER REQUEST TYPES*/
#define UDS_DEFINE_BY_ID 0x01
#define UDS_DEFINE_BY_MEM_ADDRESS 0x02
#define UDS_CLEAR_DYNAMICALLY_DEFINED_DATA_ID 0x03

/*DATA IDENTIFIER PARAMETERS*/
//0100-A5FF IS VEHICLE MANUFACTURER SPECIFIC
//A600-A7FF IS RESERVED FOR LEGISLATIVE USE
//A800-ACFF IS VEHICLE MANUFACTURER SPECIFIC
//AD00-AFFF IS LEGISLATIVE USE
//B000-B1FF IS VEHICLE MANUFACTURER SPECIFIC
//B200-BFFF IS LEGISLATIVE USE
//C000-C2FF IS VEHICLE MANUFACTURER SPECIFIC
//C300-CEFF IS LEGISLATIVE USE
//CF00-EFFF IS VEHICLE MANUFACTURER SPECIFIC
//F000-F00F IS NETWORK CONFIG DATA FOR TRACTOR TRAILER APPLICATION DATA ID
//F000-F00F IS NETWORK CONFIGURATION DATA FOR TRACTOR TRAILER APPLICATION DATA ID
//F010-F0FF IS VEHICLE MANUFACTURER SPECIFIC
//F100-F17F IS IDENTIFICATION OPTION VEHICLE MANUFACTURER SPECIFIC DATA ID
#define UDS_BOOT_SW_ID 0xF180
#define UDS_APP_SW_ID 0xF181
#define UDS_APP_DATA_ID 0xF182
#define UDS_BOOT_SW_FINGERPRINT 0xF183
#define UDS_APP_SW_FINGERPRINT 0xF184
#define UDS_APP_DATA_FINGERPRINT 0xF185
#define UDS_ACTIVE_DIAG_SESSION 0xF186
#define UDS_VEHICLE_MANUFACTURER_SPARE_PART_NO 0xF187
#define UDS_VEHICLE_MANUFACTURER_ECU_SW_NUMBER 0xF188
#define UDS_VEHICLE_MANUFACTURER_ECU_SW_VERSION_NUMBER 0xF189
#define UDS_SYSTEM_SUPPLIER_ID 0xF18A
#define UDS_ECU_MANUFACTURING_DATE 0xF18B
#define UDS_ECU_SERIAL_NO 0xF18C
#define UDS_SUPPORTED_FUNCTIONAL_UNITS 0xF18D
#define UDS_VEHICLE_MANUFACTURER_KIT_ASSY_PART_NO 0xF18E
#define UDS_VIN 0xF190
#define UDS_VEHICLE_MANUFACTURER_ECU_HW_NO 0xF191
#define UDS_SYSTEM_SUPPLIER_ECU_HW_NO 0xF192
#define UDS_SYSTEM_SUPPLIER_HW_VERSION_NO 0xF193
#define UDS_SYSTEM_SUPPLIER_ECU_SW_NUMBER 0xF194
#define UDS_SYSTEM_SUPPLIER_ECU_SW_VERSION_NO 0xF195
#define UDS_EXHAUST_REGULATION_OR_TYPE_APPROVAL_NO 0xF196
#define UDS_SYSTEM_NAME_OR_ENGINE_TYPE 0xF197
#define UDS_REPAIR_SHOP_CODE_OR_TESTER_SERIAL_NO 0xF198
#define UDS_PROGRAMMING_DATE 0xF199
#define UDS_CALIBRATION_REPAIR_SHOP_OR_EQUIPMENT_SERIAL_NO 0xF19A
#define UDS_CALIBRATION_DATE 0xF19B
#define UDS_CALIBRATION_EQUIPMENT_SW_NUMBER 0xF19C
#define UDS_ECU_INSTALLATION_DATE 0xF19D
#define UDS_ODX_FILE 0xF19E
#define UDS_ENTITY 0xF19F
//F1A0-F1EF IS ID OPTION FOR VEHICLE MANUFACTURER SPECIFIC
//F1F0-F1FF IS ID OPTION FOR SYSTEM SUPPLIER SPECIFIC
//F200-F2FF IS PERIODIC DATA ID
//F300-F3FF IS DYNAMICALLY DEFINED DATA ID
//F400-F4FF IS OBD DATA ID, USING PIDS FROM ISO 15031-5
//F500-F5FF IS OBD DATA ID
//F600-F6FF IS OBD MONITORDATA ID, USED FOR RESULTS AS DEFINED IN ISO 15031-5
//F700-F7FF IS OBD MONITOR DATA ID
//F800-F8FF IS OBD INFO TYPE, USED FOR INFO TYPE VALUES AS DEFINED IN ISO 15031-5
//F900-F9FF IS TACHOGRAPH DATA ID, ISO 16844-7
//FA00-FA0F IS AIRBAG DEPLOYMENT DATA ID
#define UDS_NUMBER_OF_EDR_DEVICES 0xFA10
#define UDS_EDR_ID 0xFA11
#define UDS_EDR_DEVICE_ADDRESS_INFO 0xFA12
//FA13-FA18 IS EDR ENTRIES
//FA19-FAFF IS SAFETY SYSTEM DATA ID
//FB00-FCFF IS RESERVED FOR LEGISLATIVE USE
//FD00-FEFF IS SYSTEM SUPPLIER SPECIFIC
#define UDS_UDS_VERSION_DATA_IDENTIFIER 0xFF00

/*FUNCTIONAL GROUP IDENTIFIERS*/
#define UDS_DTC_FUNCTIONAL_GROUP_EMMISIONS_SYSTEMS 0x33
#define UDS_DTC_FUNCTIONAL_GROUP_SAFETY_SYSTEM 0xD0
//RANGE D1-DF IS LEGISLATIVE SYSTEM
#define UDS_DTC_FUNCTIONAL_GROUP_VOBD_SYSTEM 0xFE
#define UDS_DTC_FUNCTIONAL_GROUP_ALL 0xFF

/*REQUEST FILE TRANSFER MODE OF OPERATION TYPES*/
#define UDS_FILE_TRANSFER_ADDFILE 0x01
#define UDS_FILE_TRANSFER_DELETE_FILE 0x02
#define UDS_FILE_TRANSFER_REPLACE_FILE 0x03
#define UDS_FILE_TRANSFER_READ_FILE 0x04
#define UDS_FILE_TRANSFER_READ_DIR 0x05




/*READ DTC INFORMATION REQUEST SUB FUNCTIONS*/
#define UDS_REPORT_NUMBER_OF_DTC_BY_STATUS_MASK 0x01
#define UDS_REPORT_DTC_BY_STATUS_MASK 0x02
#define UDS_REPORT_DTC_SNAPSHOT_IDENTIFICATION 0x03
#define UDS_REPORT_DTC_SNAPSHOT_RECORD_BY_DTC_NUMBER 0x04
#define UDS_REPORT_DTC_SNAPSHOT_RECORD_BY_RECORD_NUMBER 0x05
#define UDS_REPORT_DTC_EXTENDED_DATA_RECORD_BY_DTC_NUMBER 0x06
#define UDS_REPORT_NUMBER_OF_DTC_BY_SEVERITY_MASK_RECORD 0x07
#define UDS_REPORT_DTC_BY_SEVERITY_MASK_RECORD 0x08
#define UDS_REPORT_SEVERITY_INFORMATION_OF_DTC 0x09
#define UDS_REPORT_SUPPORTED_DTC 0x0A
#define UDS_REPORT_FIRST_TEST_FAILED_DTC 0x0B
#define UDS_REPORT_FIRST_CONFIRMED_DTC 0x0C
#define UDS_REPORT_MOST_RECENT_TEST_FAILED_DTC 0x0D
#define UDS_REPORT_MOST_RECENT_CONFIRMED_DTC 0x0E
#define UDS_REPORT_MIRROR_MEMORY_DTC_BY_STATUS_MASK 0x0F
#define UDS_REPORT_MIRROR_MEMORY_DTC_EXTENDED_DATA_RECORD_BY_DTC_NUMBER 0x10
#define UDS_REPORT_NUMBER_OF_MIRROR_MEMORY_DTC_BY_STATUS_MASK 0x11
#define UDS_REPORT_NUMBER_OF_EMISSIONS_RELATED_OBD_DTC_BY_STATUS_MASK 0x12
#define UDS_REPORT_EMISSIONS_RELATED_OBD_DTC_BY_STATUS_MASK 0x13
#define UDS_REPORT_DTC_FAULT_DETECTION_COUNTER 0x14
#define UDS_REPORT_DTC_WITH_PERMANENT_STATUS 0x15
#define UDS_REPORT_DTC_EXT_DATA_RECORD_BY_RECORD_NUMBER 0x16
#define UDS_REPORT_USER_DEF_MEMORY_DTC_BY_STATUS_MASK 0x17
#define UDS_REPORT_USER_DEF_MEMORY_DTC_SNAPSHOPT_RECORD_BY_DTC_NUMBER 0x18
#define UDS_REPORT_USER_DEF_MEMORY_DTC_EXT_DATA_RECORD_BY_DTC_NUMBER 0x19
#define UDS_REPORT_WWH_OBD_DTC_BY_MASK_RECORD 0x42
#define UDS_REPORT_WWH_OBD_DTC_WITH_PERMANENT_STATUS 0x55

/*DTC EXTENDED DATA RECORD NUMBER IDS*/
//01-8F IS VEHICLE MANUFACTURER SPECIFIC
//90-EF IS LEGISLATED OBD
#define UDS_DTC_EXT_DATA_RECORD_LEGISLATED_ALL 0xFE
#define UDS_DTC_EXT_DATA_RECORD_ALL 0xFF

/*DTC FORMAT IDENTIFIERS*/
#define UDS_DTC_FORMAT_SAE_J2012_DA_DTC_FORMAT_00 0x00 //DEFINED IN ISO 15031-6
#define UDS_DTC_FORMAT_ISO_14229_1_DTC_FORMAT 0x01
#define UDS_DTC_FORMAT_SAE_J1939_73_DTC_FORMAT 0x02 //PER SAE J1939-73
#define UDS_DTC_FORMAT_ISO_11992_4_DTC_FORMAT 0x03 //AS PER ISO 11992
#define UDS_DTC_FORMAT_SAE_J2012_DA_DTC_FORMAT_04 0x04 //AS PER ISO 27145-2



/*SCALING BYTE HIGH NIBBLE PARAMETERS*/
#define UDS_UNSIGNED_NUMERIC 0x0
#define UDS_SIGNED_NUMERIC 0x01
#define UDS_BITMAPPED_REPORTED_WITHOUT_MASK 0x02
#define UDS_BITMAPPED_REPORTED_WITH_MASK 0x03
#define UDS_BINARY_CODED_DECIMAL 0x04
#define UDS_STATE_ENCODED_VARIABLE 0x05
#define UDS_ASCII 0x06
#define UDS_SIGNED_FLOATING_POINT 0x07
#define UDS_PACKET 0x08
#define UDS_FORMULA 0x09
#define UDS_UNIT_FORMAT 0x0A
#define UDS_STATE_AND_CONNECTION_TYPE 0x0B


/*SCALING BYTE EXTENSION UNIT/FORMAT TYPES*/
#define UDS_NO_UNIT 0x00
#define UDS_UNIT_METER 0x01
#define UDS_UNIT_FOOT 0x02
#define UDS_UNIT_INCH 0x03
#define UDS_UNIT_YARD 0x04
#define UDS_UNIT_MILE 0x05
#define UDS_UNIT_GRAM 0x06
#define UDS_UNIT_TON 0x07
#define UDS_UNIT_SECOND 0x08
#define UDS_UNIT_MINUTE 0x09
#define UDS_UNIT_HOUR 0x0A
#define UDS_UNIT_DAY 0x0B
#define UDS_UNIT_YEAR 0x0C
#define UDS_UNIT_AMPERE 0x0D
#define UDS_UNIT_VOLT 0x0E
#define UDS_UNIT_COULOMB 0x0F
#define UDS_UNIT_OHM 0x10
#define UDS_UNIT_FARAD 0x11
#define UDS_UNIT_HENRY 0x12
#define UDS_UNIT_SIEMENS 0x13
#define UDS_UNIT_WEBER 0x14
#define UDS_UNIT_TESLA 0x15
#define UDS_UNIT_KELVIN 0x16
#define UDS_UNIT_CELSIUS 0x17
#define UDS_UNIT_FARENHEIT 0x18
#define UDS_UNIT_CANDELA 0x19
#define UDS_UNIT_RADIAN 0x1A
#define UDS_UNIT_DEGREE 0x1B
#define UDS_UNIT_HERTZ 0x1C
#define UDS_UNIT_JOULE 0x1D
#define UDS_UNIT_NEWTON 0x1E
#define UDS_UNIT_KILOPOND 0x1F
#define UDS_UNIT_LBF 0x20
#define UDS_UNIT_WATT 0x21
#define UDS_UNIT_HORSE_POWER_METRIC 0x22
#define UDS_UNIT_HORSE_POWER_UK 0x23
#define UDS_UNIT_PASCAL 0x24
#define UDS_UNIT_BAR 0x25
#define UDS_UNIT_ATMOSPHERE 0x26
#define UDS_UNIT_PSI 0x27
#define UDS_UNIT_BECQEREL 0x28
#define UDS_UNIT_LUMEN 0x29
#define UDS_UNIT_LUX 0x2A
#define UDS_UNIT_LITER 0x2B
#define UDS_UNIT_BRITISH_GALLON 0x2C
#define UDS_UNIT_US_GALLON 0x2D
#define UDS_UNIT_CUBIC_INCH 0x2E
#define UDS_UNIT_METER_PER_SECOND 0x2F
#define UDS_UNIT_KM_PER_HOUR 0x30
#define UDS_UNIT_MPH 0x31
#define UDS_UNIT_REV_PER_SEC 0x32
#define UDS_UNIT_REV_PER_MIN 0x33
#define UDS_UNIT_COUNTS 0x34
#define UDS_UNIT_PERCENT 0x35
#define UDS_UNIT_MG_PER_STROKE 0x36
#define UDS_UNIT_METER_PER_SQUARE_SECOND 0x37
#define UDS_UNIT_NM 0x38
#define UDS_UNIT_LITER_PER_MIN 0x39
#define UDS_UNIT_WATT_PER_SQUARE_M 0x3A
#define UDS_UNIT_BAR_PER_SECOND 0x3B
#define UDS_UNIT_RADIANS_PER_SECOND 0x3C
#define UDS_UNIT_RADIANS_PER_SQUARE_SECOND 0x3D
#define UDS_UNIT_KILOGRAM_PER_SQUARE_METER 0x3E
#define UDS_UNIT_PREFIX_EXA 0x40
#define UDS_UNIT_PREFIX_PETA 0x41
#define UDS_UNIT_PREFIX_TERA 0x42
#define UDS_UNIT_PREFIX_GIGA 0x43
#define UDS_UNIT_PREFIX_MEGA 0x44
#define UDS_UNIT_PREFIX_KILO 0x45
#define UDS_UNIT_PREFIX_HECTO 0x46
#define UDS_UNIT_PREFIX_DECA 0x47
#define UDS_UNIT_PREFIX_DECI 0x48
#define UDS_UNIT_PREFIX_CENTI 0x49
#define UDS_UNIT_PREFIX_MILI 0x4A
#define UDS_UNIT_PREFIX_MICRO 0x4B
#define UDS_UNIT_PREFIX_NANO 0x4C
#define UDS_UNIT_PREFIX_PICO 0x4D
#define UDS_UNIT_PREFIX_FEMTO 0x4E
#define UDS_UNIT_PREFIX_ATTO 0x4F
#define UDS_UNIT_DATE1 0x50 //YEAR-MONTH-DAY
#define UDS_UNIT_DATE2 0x51 //DAY/MONTH/YEAR
#define UDS_UNIT_DATE3 0x52 //MONTH/DAY/YEAR
#define UDS_UNIT_WEEK 0x53
#define UDS_UNIT_TIME1 0x54 //UTC HOUR/MINUTE/SECOND
#define UDS_UNIT_TIME2 0x55 //HOUR/MINUTE/SECOND
#define UDS_UNIT_DATE_AND_TIME1 0x56 //SECOND/MINUTE/HOUR/DAY/MONTH/YEAR
#define UDS_UNIT_DATE_AND_TIME2 0x57 //SECOND/MINUTE/HOUR/DAY/MONTH/YEAR/LOCAL MINUTE OFFSET/LOCAL HOUR OFFSET
#define UDS_UNIT_DATE_AND_TIME3 0x58 //SECOND/MINUTE/HOUR/MONTH/DAY/YEAR
#define UDS_UNIT_DATE_AND_TIME4 0x59 //SECOND/MINUTE/HOUR/MONTH/DAY/YEAR/LOCAL MINUTE OFFSET/LOCAL HOUR OFFSET

/*SCALING BYTE EXTENSION SUB STATE AND CONNECTION TYPE*/
//BITS 0-2
#define UDS_STATE_NOT_ACTIVE 0x0
#define UDS_STATE_ACTIVE_FUNCTION_1 0x01
#define UDS_STATE_ERROR_DETECTED 0x02
#define UDS_STATE_NOT_AVAILABLE 0x03
#define UDS_STATE_ACTIVE_FUNCTION_2 0x04
//BITS 3-4
#define UDS_STATE_SIGNAL_AT_LOW_LEVEL 0x0
#define UDS_STATE_SIGNAL_AT_MIDDLE_LEVEL 0x01
#define UDS_STATE_SIGNAL_AT_HIGH_LEVEL 0x02
//BIT 5
#define UDS_STATE_INPUT_SIGNAL 0x00
#define UDS_STATE_NOT_DEFINED 0x01
//BITS 6-7
#define UDS_STATE_INTERNAL_SIGNAL_NOT_EXCLUSIVELY_AVAILABLE_IN_ECU_CONNECTOR 0x00
#define UDS_STATE_PULL_DOWN_RESISTOR_INPUT_TYPE 0x1
#define UDS_STATE_PULL_UP_RESISTOR_INPUT_TYPE 0x02
#define UDS_STATE_PULL_UP_AND_PULL_DOWN_RESISTOR_INPUT_TYPE 0x03

/*TRANSMISSION MODE PARAMETERS*/
#define UDS_TRANSMISSION_SEND_AT_SLOW_RATE 0x01
#define UDS_TRANSMISSION_SEND_AT_MEDIUM_RATE 0x02
#define UDS_TRANSMISSION_SEND_AT_FAST_RATE 0x03
#define UDS_TRANSMISSION_STOP_SENDING 0x04

/*GROUP OF DTC PARAMETERS*/
#define UDS_DTC_GENERIC_EMISSIONS 0x000000
#define UDS_DTC_GENERIC_ALL_GROUPS 0xFFFFFF
//THE REST OF GROUPS ARE DETERMINED BY VEHICLE MANUFACTURER

/*DTC STATUS PARAMETERS*/
//BIT 0
#define UDS_DTC_STATUS_TEST_FAILED_BIT 0x0
#define UDS_DTC_STATUS_TEST_FAILED_FALSE 0x0
#define UDS_DTC_STATUS_TEST_FAILED_TRUE 0x1
//BIT 1
#define UDS_DTC_STATUS_TEST_FAILED_THIS_OPERATION_CYCLE_BIT 0x01
#define UDS_DTC_STATUS_TEST_FAILED_THIS_OPERATION_CYCLE_FALSE 0x0
#define UDS_DTC_STATUS_TEST_FAILED_THIS_OPERATION_CYCLE_TRUE 0x1
//BIT 2
#define UDS_DTC_STATUS_PENDING_DTC_BIT 0x02
#define UDS_DTC_STATUS_PENDING_DTC_FALSE 0x0
#define UDS_DTC_STATUS_PENDING_DTC_TRUE 0x1
//BIT 3
#define UDS_DTC_STATUS_CONFIRMED_DTC_BIT 0x03
#define UDS_DTC_STATUS_CONFIRMED_DTC_FALSE 0x0
#define UDS_DTC_STATUS_CONFIRMED_DTC_TRUE 0x1
//BIT 4
#define UDS_DTC_STATUS_TEST_NOT_COMPLETE_SINCE_LAST_CLEAR_BIT 0x04
#define UDS_DTC_STATUS_TEST_NOT_COMPLETE_SINCE_LAST_CLEAR_FALSE 0x0
#define UDS_DTC_STATUS_TEST_NOT_COMPLETE_SINCE_LAST_CLEAR_TRUE 0x01
//BIT_5
#define UDS_DTC_STATUS_TEST_FAILED_SINCE_LAST_CLEAR_BIT 0x05
#define UDS_DTC_STATUS_TEST_FAILED_SINCE_LAST_CLEAR_FALSE 0x0
#define UDS_DTC_STATUS_TEST_FAILED_SINCE_LAST_CLEAR_TRUE 0x01
//BIT 6
#define UDS_DTC_STATUS_TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE_BIT 0x06
#define UDS_DTC_STATUS_TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE_FALSE 0x00
#define UDS_DTC_STATUS_TEST_NOT_COMPLETED_THIS_OPERATION_CYCLE_TRUE 0x01
//BIT 7
#define UDS_DTC_STATUS_WARNING_INDICATOR_REQUESTED_BIT 0x07
#define UDS_DTC_STATUS_WARNING_INDICATOR_REQUESTED_FALSE 0x00
#define UDS_DTC_STATUS_WARNING_INDICATOR_REQUESTED_TRUE 0x01

/*DTC SEVERITY VALUES*/
#define UDS_DTC_SEVERITY_NO_SEVERITY_AVAILABLE 0x0
#define UDS_DTC_SEVERITY_MAINTENANCE_ONLY 0x20
#define UDS_DTC_SEVERITY_CHECK_AT_NEXT_HALT 0x40
#define UDS_DTC_SEVERITY_CHECK_IMMEDIATELY 0x80

/*INPUT OUTPUT CONTROL PARAMETER DEFINITIONS*/
#define UDS_IO_CONTROL_RETURN_CONTROL_TO_ECU 0x00
#define UDS_IO_CONTROL_RESET_TO_DEFAULT 0x01
#define UDS_IO_CONTROL_FREEZE_CURRENT_STATE 0x02
#define UDS_IO_CONTROL_SHORT_TERM_ADJUSTMENT 0x03

/*ROUTINE ID ROUTINES*/
//RANGE 0x0100-01FF ARE TACOGRAPH TEST IDS
//RANGE 0x0200-DFFF ARE VEHICLE MANUFACTURER SPECIFIC
//RANGE 0xE000-E1FF ARE OBD TEST IDS
#define UDS_ROUTINE_DEPLOY_LOOP_ROUTINE_ID 0xE200
//RANGE 0xE201-E2FF SAFETY SYSTEM ROUTINE IDS
//RANGE 0xF000-FEFF SYSTEM SUPPLIER SPECIFIC
#define UDS_ROUTINE_ERASE_MEMORY 0xFF00
#define UDS_ROUTINE_CHECK_PROGRAMMING_DEPENDENCIES 0xFF01
#define UDS_ROUTINE_ERASE_MIRROR_MEMORY_DTCS 0xFF02

/*IO CONTROL BY ID DATA IDENTIFIER VALUES*/
#define UDS_IO_CONTROL_DISABLE_IAC_AND_EGR_CONTROL 0x0100
#define UDS_IO_CONTROL_CONTROL_IAC_PINTLE_POSITION_DISABLE_EGR_CONTROL 0x0101
#define UDS_IO_CONTROL_DISABLE_IAC_CONTROL_AND_EGR_CONTROL 0x0102
#define UDS_IO_CONTROL_CONTROL_IAC_RPM_DISABLE_EGR_CONTROL 0x0103
#define UDS_IO_CONTROL_CONTROL_EGR_DUTY_CYCLE_DISABLE_IAC_CONTROL 0x0104
#define UDS_IO_CONTROL_CONTROL_EGR_DUTY_CYCLE_AND_IAC_PINTLE_POSITION 0x0105
#define UDS_IO_CONTROL_CONTROL_EGR_DUTY_CYCLE_DISABLE_IAC_CONTROL2 0x0106
#define UDS_IO_CONTROL_CONTROL_EGR_DUTY_CYCLE_AND_IAC_RPM 0x0107

/*ROUTINE CONTROL SUB-FUNCTIONS*/
#define UDS_START_ROUTINE 0x01
#define UDS_STOP_ROUTINE 0x02
#define UDS_REQUEST_ROUTINE_RESULTS 0x03

/*REQUEST UPLOAD/DOWNLOAD DATA FORMAT IDENTIFIER*/
#define UDS_NO_ENCRYPTION 0x00
//ANY OTHER VALUE THAN 0 MEANS WHATEVER METHOD, AND IS MANUFACTURER SPECIFIC
